# Анна Пермякова

![Логотип](images/Пермякова%20А.В.png?raw=true)

##  Data science  

Опыт работы с медицинскими данными 5 лет+, медицинская статистика, анализ данных, прогнозирование  
Имею опыт построения классификационных, регрессионных и кластеризационных моделей с использованием ML/DL‑подходы и инструменты. Numpy, scikit-learn, pandas, Pytorch/TensorFlow. Git, разработка функций, Docker. Математическая статистика, линейная алгебра и теория вероятностей.  
Образование МФТИ, 2024. Прикладная математика и физика.

[Просмотреть мой профиль LinkedIn](https://www.linkedin.com/in/анна-пермякова-a5b4ba230/)

![Логотип МФТИ](images/logo_МФТИ.png?raw=true)
