title: Анна Пермякова
description: Data Scientist 
theme: minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# URL-адрес логотипа
logo: /images/Пермякова%20А.В.png

# Описание сайта
description: Опыт работы с медицинскими данными, медицинская статистика, анализ данных, прогнозирование

# Ссылка на профиль LinkedIn
linkedin: https://www.linkedin.com/in/анна-пермякова-a5b4ba230/

# Идентификатор отслеживания Google Analytics
google_analytics: UA-000000-0

